### ISSUE TITLE
djangorestframeworks 3.9 SchemaGenerator does not have get_path_fields method

### ISSUE THREAD

**Issue by naughtyGitCat** [m-haziq/django-rest-swagger-docs#10]
djangorestframeworks 3.9 SchemaGenerator does not have get_path_fields method

**Comment by naughtyGitCat** [comment]
ether 
get_serializer_fields
get_pagination_fields
get_filter_fields
get_encoding

**Comment by m-haziq** [comment]
Hi @naughtyGitCat , this documentation is only compatible with `djangorestframework==3.5.3` and `django-rest-swagger==2.1.1`. Please refer to read me for further info. I have not actually take out time yet to write  a doc for latest swagger and django-rest .
