### ISSUE TITLE
I can not find how to defining parameters in CBV.

### ISSUE THREAD

**Issue by cg831344** [m-haziq/django-rest-swagger-docs#2]
Can you help me

**Comment by m-haziq** [comment]
Yes, Django Rest Swagger 2.0 automatically creates parameters for CBVs on the basis of your serializers.py . Look at these files `demo/cbv_demo/models.py` and `demo/cbv_demo/serializers.py` . This model serializer helps swagger to create parameters. On the other hand if you do not want to use serializer then you can use YAML to define parameters after implementing this: https://github.com/m-haziq/django-rest-swagger-docs#advance-usage

**Comment by cg831344** [comment]
Ok.Think you
