### ISSUE TITLE
Swagger in Django rest function based api does not show properly on ubuntu server (production)

### ISSUE THREAD

**Issue by axilaris** [m-haziq/django-rest-swagger-docs#4]
I am having this problem that is posted in stackoverflow. How can I debug and resolve this issue ? Thanks.

https://stackoverflow.com/questions/47566978/swagger-in-django-rest-function-based-api-does-not-show-properly-on-ubuntu-serve

**Comment by m-haziq** [comment]
Try setting your STATICFILES_DIR in your settings.py as I answered here:
https://stackoverflow.com/questions/47566978/swagger-in-django-rest-function-based-api-does-not-show-properly-on-ubuntu-serve/47573846#answer-47573846
