### ISSUE TITLE
Swagger not loading on AWS

### ISSUE THREAD

**Issue by NavchetanKaur** [m-haziq/django-rest-swagger-docs#6]
I have a django tool hosted on AWS  as http://www.transplanttoolbox.org/. I have web services too for this tool and can be accessed through urls like http://www.transplanttoolbox.org/array/, http://www.transplanttoolbox.org/single_allele/, http://www.transplanttoolbox.org/gls/ etc. 

I have added Swagger UI for these web services at http://www.transplanttoolbox.org/tool_services, but the swagger schema is not loading on that page in production, though everything is perfect in development.

**Comment by m-haziq** [comment]
I have debugged your swagger URL, seems like it is unable to find the static files:
![screenshot from 2017-12-28 10-52-58](https://user-images.githubusercontent.com/20089858/34401557-e3178a38-ebbd-11e7-9af8-8c6b23e12307.png)

 Try running `collectstatic` command, or try this: [solution](https://stackoverflow.com/questions/47566978/swagger-in-django-rest-function-based-api-does-not-show-properly-on-ubuntu-serve/47573846#47573846)

**Comment by NavchetanKaur** [comment]
Thank you!! It worked with collectstatic.
