### ISSUE TITLE
can't add parameter descriptions

### ISSUE THREAD

**Issue by danielmanatal** [m-haziq/django-rest-swagger-docs#8]
I did the override according to the document but it still doesn't work.

This is my views.py
```

class JobIndustryOfJobViewSet(ModelViewSet):
"""
description: A viewset for viewing and editing industries of a job.
parameters:
  - name: job_pk
    type: string
    required: true
    location: path
"""

serializer_class = JobIndustryOfJobSerializer

def get_queryset(self):
    """
    Filter by current user's client and parent object
    """
    job = get_object_or_404(
        get_job_queryset(self.request.user), pk=self.kwargs.get("job_pk")
    )
    return JobIndustry.objects.filter(job=job).select_related("industry")

```
And it still don't show the parameter descriptions in the Swagger UI:

I also ask the same question in here:
https://stackoverflow.com/questions/56167085/django-swagger-cant-add-parameter-descriptions

**Comment by m-haziq** [comment]
@danielmanatal Can you share your django, django-rest, and django-rest-swagger  versions?

**Comment by danielmanatal** [comment]
Django==2.2.1

djangorestframework==3.9.4
django-rest-swagger==2.2.0


Thank You

**Comment by m-haziq** [comment]
This documentation is customized and only works on specific versions, try using:

django-rest-swagger==2.1.1
djangorestframework==3.5.3

This is mentioned in the doc clearly. Reopen the ticket if you find any other issue.

________________________________
